### - PLain read
GET http://localhost:9000/todos
Content-type: application/json

### - Create TODO with incomplete parameters
POST http://localhost:9000/todos
Content-type: application/json

{}

### - Create TODO
POST http://localhost:9000/todos
Content-type: application/json
{
    "title" : "Todo Title",
    "description" : "Todo Description"
}

### -
PUT http://localhost:9000/todos/067e6162-3b6f-4ae2-a171-2470b63dff00/complete
Content-type: application/json

{
    "isCompleted" : true
}

###
PUT http://localhost:9000/todos/067e6162-3b6f-4ae2-a171-2470b63dff00/complete
Content-type: application/json

{
    "isCompleted" : false
}

###
DELETE http://localhost:9000/todos/067e6162-3b6f-4ae2-a171-2470b63dff00

###